ALTER TABLE REDOURCES RENAME TO RESOURCES;

SELECT * FROM user_sequences;

select * from restype;

--자원종류sequences;
create sequence restype_seq
increment by 1
start with 4
nocache;

--자원종류
insert into restype(type_no, type_name)
values(1,'회의실');
insert into restype(type_no, type_name)
values(2,'차량');
insert into restype(type_no, type_name)
values(3,'리조트');

--자원sequences;
create sequence res_seq
increment by 1
start with 1
nocache;

--자원테이블
INSERT INTO RESOURCES(RES_NO, TYPE_NO, RES_NAME, RES_LOCATION)
VALUES(RES_SEQ.nextval,1,'A회의실','본관1층');
INSERT INTO RESOURCES(RES_NO, TYPE_NO, RES_NAME, RES_LOCATION)
VALUES(RES_SEQ.nextval,1,'B회의실','본관2층');
INSERT INTO RESOURCES(RES_NO, TYPE_NO, RES_NAME, RES_LOCATION)
VALUES(RES_SEQ.nextval,1,'C회의실','본관3층');
INSERT INTO RESOURCES(RES_NO, TYPE_NO, RES_NAME, RES_LOCATION)
VALUES(RES_SEQ.nextval,2,'아반떼','본관지하1층');
INSERT INTO RESOURCES(RES_NO, TYPE_NO, RES_NAME, RES_LOCATION)
VALUES(RES_SEQ.nextval,2,'카니발','별관지하2층');
INSERT INTO RESOURCES(RES_NO, TYPE_NO, RES_NAME, RES_LOCATION)
VALUES(RES_SEQ.nextval,2,'쏘나타','본관지하2층');
INSERT INTO RESOURCES(RES_NO, TYPE_NO, RES_NAME, RES_LOCATION)
VALUES(RES_SEQ.nextval,3,'W리조트','경기도');
INSERT INTO RESOURCES(RES_NO, TYPE_NO, RES_NAME, RES_LOCATION)
VALUES(RES_SEQ.nextval,3,'I리조트','강원도');
INSERT INTO RESOURCES(RES_NO, TYPE_NO, RES_NAME, RES_LOCATION)
VALUES(RES_SEQ.nextval,3,'R리조트','제주도');

SELECT * FROM RESOURCES;

--자원리스트 VIEW
CREATE OR REPLACE VIEW JAWONLIST_VIEW
AS
(
    SELECT T.TYPE_NAME, R.*, S.MEM_NO, S.RESERV_NO, 
    S.USE_REGDATE,S.RETURN_REGDATE,S.RESERV_CONTENT
    FROM RESTYPE T JOIN RESOURCES R
    ON T.TYPE_NO=R.TYPE_NO
    JOIN RESSCHEDULE S
    ON R.RES_NO=S.RES_NO
);

--자원=사원 VIEW
CREATE OR REPLACE VIEW JAWONMEM_VIEW
AS
(
    SELECT T.*, R.RES_NAME, R.RES_NO, S.USE_REGDATE, S.RETURN_REGDATE,
    S.RESERV_CONTENT, D.DEPT_NAME, S.RESERV_NO
    FROM RESTYPE T JOIN RESOURCES R
    ON T.TYPE_NO=R.TYPE_NO
    JOIN RESSCHEDULE S
    ON S.RES_NO=R.RES_NO
    JOIN MEMBER M
    ON M.MEM_NO=S.MEM_NO
    JOIN DEPARTMENT D
    ON D.DEPT_NO=M.DEPT_NO
);


