ALTER TABLE "MEMBER"
	DROP
		CONSTRAINT "FK_RANKS_TO_MEMBER"
		CASCADE;

ALTER TABLE "MEMBER"
	DROP
		CONSTRAINT "FK_DEPARTMENT_TO_MEMBER"
		CASCADE;

ALTER TABLE "MEMBER"
	DROP
		CONSTRAINT "FK_POSITION_TO_MEMBER"
		CASCADE;

ALTER TABLE "ADDRESSBOOK"
	DROP
		CONSTRAINT "FK_MEMBER_TO_ADDRESSBOOK"
		CASCADE;

ALTER TABLE "BOARD"
	DROP
		CONSTRAINT "FK_MEMBER_TO_BOARD"
		CASCADE;

ALTER TABLE "BOARD"
	DROP
		CONSTRAINT "FK_BOARDLIST_TO_BOARD"
		CASCADE;

ALTER TABLE "BOARDLIST"
	DROP
		CONSTRAINT "FK_RANKS_TO_BOARDLIST"
		CASCADE;

ALTER TABLE "REPLY"
	DROP
		CONSTRAINT "FK_MEMBER_TO_REPLY"
		CASCADE;

ALTER TABLE "REPLY"
	DROP
		CONSTRAINT "FK_BOARD_TO_REPLY"
		CASCADE;

ALTER TABLE "CONFIRMLINE"
	DROP
		CONSTRAINT "FK_MEMBER_TO_CONFIRMLINE"
		CASCADE;

ALTER TABLE "CONFIRMLINE"
	DROP
		CONSTRAINT "FK_LINEREG_TO_CONFIRMLINE"
		CASCADE;

ALTER TABLE "REDOURCES"
	DROP
		CONSTRAINT "FK_RESTYPE_TO_REDOURCES"
		CASCADE;

ALTER TABLE "RESSCHEDULE"
	DROP
		CONSTRAINT "FK_MEMBER_TO_RESSCHEDULE"
		CASCADE;

ALTER TABLE "RESSCHEDULE"
	DROP
		CONSTRAINT "FK_REDOURCES_TO_RESSCHEDULE"
		CASCADE;

ALTER TABLE "COMMUTE"
	DROP
		CONSTRAINT "FK_MEMBER_TO_COMMUTE"
		CASCADE;

ALTER TABLE "CONFIRMFILE"
	DROP
		CONSTRAINT "FK_CONFIRM_TO_CONFIRMFILE"
		CASCADE;

ALTER TABLE "WEBHARDFILE"
	DROP
		CONSTRAINT "FK_WEBHARD_TO_WEBHARDFILE"
		CASCADE;

ALTER TABLE "WEBHARDFILE"
	DROP
		CONSTRAINT "FK_MEMBER_TO_WEBHARDFILE"
		CASCADE;

ALTER TABLE "LINEREG"
	DROP
		CONSTRAINT "FK_MEMBER_TO_LINEREG"
		CASCADE;

ALTER TABLE "SIGNREG"
	DROP
		CONSTRAINT "FK_MEMBER_TO_SIGNREG"
		CASCADE;

ALTER TABLE "CONFIRM"
	DROP
		CONSTRAINT "FK_MEMBER_TO_CONFIRM"
		CASCADE;

ALTER TABLE "CONFIRM"
	DROP
		CONSTRAINT "FK_DEPARTMENT_TO_CONFIRM"
		CASCADE;

ALTER TABLE "CONFIRM"
	DROP
		CONSTRAINT "FK_LINEREG_TO_CONFIRM"
		CASCADE;

ALTER TABLE "CONFIRM"
	DROP
		CONSTRAINT "FK_DOCFORM_TO_CONFIRM"
		CASCADE;

ALTER TABLE "DOCFORM"
	DROP
		CONSTRAINT "FK_DOCTYPE_TO_DOCFORM"
		CASCADE;

ALTER TABLE "DOCFORM"
	DROP
		CONSTRAINT "FK_RANKS_TO_DOCFORM"
		CASCADE;

ALTER TABLE "MAIL"
	DROP
		CONSTRAINT "FK_MEMBER_TO_MAIL"
		CASCADE;

ALTER TABLE "SCHEDULE"
	DROP
		CONSTRAINT "FK_MEMBER_TO_SCHEDULE"
		CASCADE;

ALTER TABLE "TEAMSCHEDULE"
	DROP
		CONSTRAINT "FK_MEMBER_TO_TEAMSCHEDULE"
		CASCADE;

ALTER TABLE "TEAMSCHEDULE"
	DROP
		CONSTRAINT "FK_DEPARTMENT_TO_TEAMSCHEDULE"
		CASCADE;

ALTER TABLE "MSGREV"
	DROP
		CONSTRAINT "FK_MESSAGE_TO_MSGREV"
		CASCADE;

ALTER TABLE "MSGREV"
	DROP
		CONSTRAINT "FK_MEMBER_TO_MSGREV"
		CASCADE;

ALTER TABLE "MESSAGE"
	DROP
		CONSTRAINT "FK_MEMBER_TO_MESSAGE"
		CASCADE;

ALTER TABLE "MEMBER"
	DROP
		PRIMARY KEY
		CASCADE
		KEEP INDEX;

ALTER TABLE "RANKS"
	DROP
		PRIMARY KEY
		CASCADE
		KEEP INDEX;

ALTER TABLE "DEPARTMENT"
	DROP
		PRIMARY KEY
		CASCADE
		KEEP INDEX;

ALTER TABLE "ADDRESSBOOK"
	DROP
		PRIMARY KEY
		CASCADE
		KEEP INDEX;

ALTER TABLE "BOARD"
	DROP
		PRIMARY KEY
		CASCADE
		KEEP INDEX;

ALTER TABLE "BOARDLIST"
	DROP
		PRIMARY KEY
		CASCADE
		KEEP INDEX;

ALTER TABLE "REPLY"
	DROP
		PRIMARY KEY
		CASCADE
		KEEP INDEX;

ALTER TABLE "CONFIRMLINE"
	DROP
		PRIMARY KEY
		CASCADE
		KEEP INDEX;

ALTER TABLE "REDOURCES"
	DROP
		PRIMARY KEY
		CASCADE
		KEEP INDEX;

ALTER TABLE "RESSCHEDULE"
	DROP
		PRIMARY KEY
		CASCADE
		KEEP INDEX;

ALTER TABLE "RESTYPE"
	DROP
		PRIMARY KEY
		CASCADE
		KEEP INDEX;

ALTER TABLE "COMMUTE"
	DROP
		PRIMARY KEY
		CASCADE
		KEEP INDEX;

ALTER TABLE "WEBHARD"
	DROP
		PRIMARY KEY
		CASCADE
		KEEP INDEX;

ALTER TABLE "CONFIRMFILE"
	DROP
		PRIMARY KEY
		CASCADE
		KEEP INDEX;

ALTER TABLE "WEBHARDFILE"
	DROP
		PRIMARY KEY
		CASCADE
		KEEP INDEX;

ALTER TABLE "LINEREG"
	DROP
		PRIMARY KEY
		CASCADE
		KEEP INDEX;

ALTER TABLE "SIGNREG"
	DROP
		PRIMARY KEY
		CASCADE
		KEEP INDEX;

ALTER TABLE "CONFIRM"
	DROP
		PRIMARY KEY
		CASCADE
		KEEP INDEX;

ALTER TABLE "DOCFORM"
	DROP
		PRIMARY KEY
		CASCADE
		KEEP INDEX;

ALTER TABLE "DOCTYPE"
	DROP
		PRIMARY KEY
		CASCADE
		KEEP INDEX;

ALTER TABLE "MAIL"
	DROP
		PRIMARY KEY
		CASCADE
		KEEP INDEX;

ALTER TABLE "POSITION"
	DROP
		PRIMARY KEY
		CASCADE
		KEEP INDEX;

ALTER TABLE "SCHEDULE"
	DROP
		PRIMARY KEY
		CASCADE
		KEEP INDEX;

ALTER TABLE "TEAMSCHEDULE"
	DROP
		PRIMARY KEY
		CASCADE
		KEEP INDEX;

ALTER TABLE "MSGREV"
	DROP
		PRIMARY KEY
		CASCADE
		KEEP INDEX;

ALTER TABLE "MESSAGE"
	DROP
		PRIMARY KEY
		CASCADE
		KEEP INDEX;

DROP INDEX "PK_MEMBER";

DROP INDEX "PK_RANKS";

DROP INDEX "PK_DEPARTMENT";

DROP INDEX "PK_ADDRESSBOOK";

DROP INDEX "PK_BOARD";

DROP INDEX "PK_BOARDLIST";

DROP INDEX "PK_REPLY";

DROP INDEX "PK_CONFIRMLINE";

DROP INDEX "PK_REDOURCES";

DROP INDEX "PK_RESSCHEDULE";

DROP INDEX "PK_RESTYPE";

DROP INDEX "PK_COMMUTE";

DROP INDEX "PK_WEBHARD";

DROP INDEX "PK_CONFIRMFILE";

DROP INDEX "PK_WEBHARDFILE";

DROP INDEX "PK_LINEREG";

DROP INDEX "PK_SIGNREG";

DROP INDEX "PK_CONFIRM";

DROP INDEX "PK_DOCFORM";

DROP INDEX "PK_DOCTYPE";

DROP INDEX "PK_MAIL";

DROP INDEX "PK_POSITION";

DROP INDEX "PK_SCHEDULE";

DROP INDEX "PK_TEAMSCHEDULE";

DROP INDEX "PK_MSGREV";

DROP INDEX "PK_MESSAGE";

/* 사원정보 */
DROP TABLE "MEMBER" 
	CASCADE CONSTRAINTS;

/* 사원등급 */
DROP TABLE "RANKS" 
	CASCADE CONSTRAINTS;

/* 부서 */
DROP TABLE "DEPARTMENT" 
	CASCADE CONSTRAINTS;

/* 주소록 */
DROP TABLE "ADDRESSBOOK" 
	CASCADE CONSTRAINTS;

/* 게시글목록 */
DROP TABLE "BOARD" 
	CASCADE CONSTRAINTS;

/* 게시판목록 */
DROP TABLE "BOARDLIST" 
	CASCADE CONSTRAINTS;

/* 댓글 */
DROP TABLE "REPLY" 
	CASCADE CONSTRAINTS;

/* 결재라인 */
DROP TABLE "CONFIRMLINE" 
	CASCADE CONSTRAINTS;

/* 자원 */
DROP TABLE "REDOURCES" 
	CASCADE CONSTRAINTS;

/* 자원스케줄 */
DROP TABLE "RESSCHEDULE" 
	CASCADE CONSTRAINTS;

/* 자원종류 */
DROP TABLE "RESTYPE" 
	CASCADE CONSTRAINTS;

/* 근태관리 */
DROP TABLE "COMMUTE" 
	CASCADE CONSTRAINTS;

/* 웹하드목록 */
DROP TABLE "WEBHARD" 
	CASCADE CONSTRAINTS;

/* 결제파일 */
DROP TABLE "CONFIRMFILE" 
	CASCADE CONSTRAINTS;

/* 웹하드파일목록 */
DROP TABLE "WEBHARDFILE" 
	CASCADE CONSTRAINTS;

/* 결재라인등록 */
DROP TABLE "LINEREG" 
	CASCADE CONSTRAINTS;

/* 결제서명등록 */
DROP TABLE "SIGNREG" 
	CASCADE CONSTRAINTS;

/* 전자결재 */
DROP TABLE "CONFIRM" 
	CASCADE CONSTRAINTS;

/* 문서양식 */
DROP TABLE "DOCFORM" 
	CASCADE CONSTRAINTS;

/* 양식종류 */
DROP TABLE "DOCTYPE" 
	CASCADE CONSTRAINTS;

/* 웹메일 */
DROP TABLE "MAIL" 
	CASCADE CONSTRAINTS;

/* 직급 */
DROP TABLE "POSITION" 
	CASCADE CONSTRAINTS;

/* 팀내스케줄 */
DROP TABLE "TABLE3" 
	CASCADE CONSTRAINTS;

/* 개인스케줄 */
DROP TABLE "SCHEDULE" 
	CASCADE CONSTRAINTS;

/* 팀스케줄 */
DROP TABLE "TEAMSCHEDULE" 
	CASCADE CONSTRAINTS;

/* 쪽지수신 */
DROP TABLE "MSGREV" 
	CASCADE CONSTRAINTS;

/* 쪽지함 */
DROP TABLE "MESSAGE" 
	CASCADE CONSTRAINTS;

/* 사원정보 */
CREATE TABLE "MEMBER" (
	"MEM_NO" NUMBER NOT NULL, /* 사원번호 */
	"RANKS_NO" NUMBER, /* 등급번호 */
	"DEPT_NO" NUMBER, /* 부서번호 */
	"MEM_NAME" VARCHAR2(30) NOT NULL, /* 이름 */
	"MEM_HP1" VARCHAR2(10) NOT NULL, /* 연락처1 */
	"MEM_HP2" VARCHAR2(10), /* 연락처2 */
	"MEM_HP3" VARCHAR2(10), /* 연락처3 */
	"MEM_EMAIL1" VARCHAR2(30), /* 이메일1 */
	"MEM_EMAIL2" VARCHAR2(30), /* 이메일2 */
	"MEM_ID" VARCHAR2(30) NOT NULL, /* 아이디 */
	"MEM_PWD" VARCHAR2(100) NOT NULL, /* 비밀번호 */
	"MEM_ZIPCODE" VARCHAR2(30), /* 우편 */
	"MEM_ADDRESS" VARCHAR2(100), /* 주소 */
	"MEM_ADDRESSDETAIL" VARCHAR2(100), /* 상세주소 */
	"MEM_FILENAME" VARCHAR2(150), /* 이미지파일명 */
	"MEM_ORIGINALFILENAME" VARCHAR2(150), /* 이미지원본파일명 */
	"MEM_JOINDATE" DATE DEFAULT SYSDATE, /* 입사일 */
	"MEM_RESIGNDATE" DATE, /* 퇴사일 */
	"MEM_PAY" NUMBER, /* 연봉 */
	"MEM_HOLIDAY" NUMBER, /* 연차 */
	"MEM_USEHOLIDAY" NUMBER, /* 사용연차 */
	"MEM_FLAG" CHAR DEFAULT N NOT NULL, /* 인증여부 */
	"POS_NO" NUMBER /* 직급번호 */
)
	STORAGE (
		BUFFER_POOL DEFAULT
	)
	LOGGING
	NOCOMPRESS
	NOCACHE
	NOPARALLEL
	NOROWDEPENDENCIES
	DISABLE ROW MOVEMENT;

COMMENT ON TABLE "MEMBER" IS '사원정보';

COMMENT ON COLUMN "MEMBER"."MEM_NO" IS '사원번호';

COMMENT ON COLUMN "MEMBER"."RANKS_NO" IS '등급번호';

COMMENT ON COLUMN "MEMBER"."DEPT_NO" IS '부서번호';

COMMENT ON COLUMN "MEMBER"."MEM_NAME" IS '이름';

COMMENT ON COLUMN "MEMBER"."MEM_HP1" IS '연락처1';

COMMENT ON COLUMN "MEMBER"."MEM_HP2" IS '연락처2';

COMMENT ON COLUMN "MEMBER"."MEM_HP3" IS '연락처3';

COMMENT ON COLUMN "MEMBER"."MEM_EMAIL1" IS '이메일1';

COMMENT ON COLUMN "MEMBER"."MEM_EMAIL2" IS '이메일2';

COMMENT ON COLUMN "MEMBER"."MEM_ID" IS '아이디';

COMMENT ON COLUMN "MEMBER"."MEM_PWD" IS '비밀번호';

COMMENT ON COLUMN "MEMBER"."MEM_ZIPCODE" IS '우편';

COMMENT ON COLUMN "MEMBER"."MEM_ADDRESS" IS '주소';

COMMENT ON COLUMN "MEMBER"."MEM_ADDRESSDETAIL" IS '상세주소';

COMMENT ON COLUMN "MEMBER"."MEM_FILENAME" IS '이미지파일명';

COMMENT ON COLUMN "MEMBER"."MEM_ORIGINALFILENAME" IS '이미지원본파일명';

COMMENT ON COLUMN "MEMBER"."MEM_JOINDATE" IS '입사일';

COMMENT ON COLUMN "MEMBER"."MEM_RESIGNDATE" IS '퇴사일';

COMMENT ON COLUMN "MEMBER"."MEM_PAY" IS '연봉';

COMMENT ON COLUMN "MEMBER"."MEM_HOLIDAY" IS '연차';

COMMENT ON COLUMN "MEMBER"."MEM_USEHOLIDAY" IS '사용연차';

COMMENT ON COLUMN "MEMBER"."MEM_FLAG" IS '인증여부';

COMMENT ON COLUMN "MEMBER"."POS_NO" IS '직급번호';

CREATE UNIQUE INDEX "PK_MEMBER"
	ON "MEMBER" (
		"MEM_NO" ASC
	)
	STORAGE (
		BUFFER_POOL DEFAULT
	)
	NOLOGGING
	NOCOMPRESS
	SORT
	NOPARALLEL;

ALTER TABLE "MEMBER"
	ADD
		CONSTRAINT "PK_MEMBER"
		PRIMARY KEY (
			"MEM_NO"
		)
		NOT DEFERRABLE
		INITIALLY IMMEDIATE
		ENABLE
		VALIDATE;

/* 사원등급 */
CREATE TABLE "RANKS" (
	"RANKS_NO" NUMBER NOT NULL, /* 등급번호 */
	"RANKS_NAME" VARCHAR2(30) NOT NULL /* 등급이름 */
)
	STORAGE (
		BUFFER_POOL DEFAULT
	)
	LOGGING
	NOCOMPRESS
	NOCACHE
	NOPARALLEL
	NOROWDEPENDENCIES
	DISABLE ROW MOVEMENT;

COMMENT ON TABLE "RANKS" IS '사원등급';

COMMENT ON COLUMN "RANKS"."RANKS_NO" IS '등급번호';

COMMENT ON COLUMN "RANKS"."RANKS_NAME" IS '등급이름';

CREATE UNIQUE INDEX "PK_RANKS"
	ON "RANKS" (
		"RANKS_NO" ASC
	)
	STORAGE (
		BUFFER_POOL DEFAULT
	)
	NOLOGGING
	NOCOMPRESS
	SORT
	NOPARALLEL;

ALTER TABLE "RANKS"
	ADD
		CONSTRAINT "PK_RANKS"
		PRIMARY KEY (
			"RANKS_NO"
		)
		NOT DEFERRABLE
		INITIALLY IMMEDIATE
		ENABLE
		VALIDATE;

/* 부서 */
CREATE TABLE "DEPARTMENT" (
	"DEPT_NO" NUMBER NOT NULL, /* 부서번호 */
	"DEPT_NAME" VARCHAR2(30) NOT NULL /* 부서이름 */
)
	STORAGE (
		BUFFER_POOL DEFAULT
	)
	LOGGING
	NOCOMPRESS
	NOCACHE
	NOPARALLEL
	NOROWDEPENDENCIES
	DISABLE ROW MOVEMENT;

COMMENT ON TABLE "DEPARTMENT" IS '부서';

COMMENT ON COLUMN "DEPARTMENT"."DEPT_NO" IS '부서번호';

COMMENT ON COLUMN "DEPARTMENT"."DEPT_NAME" IS '부서이름';

CREATE UNIQUE INDEX "PK_DEPARTMENT"
	ON "DEPARTMENT" (
		"DEPT_NO" ASC
	)
	STORAGE (
		BUFFER_POOL DEFAULT
	)
	NOLOGGING
	NOCOMPRESS
	SORT
	NOPARALLEL;

ALTER TABLE "DEPARTMENT"
	ADD
		CONSTRAINT "PK_DEPARTMENT"
		PRIMARY KEY (
			"DEPT_NO"
		)
		NOT DEFERRABLE
		INITIALLY IMMEDIATE
		ENABLE
		VALIDATE;

/* 주소록 */
CREATE TABLE "ADDRESSBOOK" (
	"ADDRBOOK_NO" NUMBER NOT NULL, /* 주소록번호 */
	"ADDRBOOK_NAME" VARCHAR2(60) NOT NULL, /* 주소록이름 */
	"ADDRBOOK_COMNAME" VARCHAR2(60), /* 회사명 */
	"ADDRBOOK_TEL" VARCHAR2(50), /* 전화번호 */
	"ADDRBOOK_EMAIL" VARCHAR2(100), /* 이메일 */
	"MEM_NO" NUMBER /* 사원번호 */
)
	STORAGE (
		BUFFER_POOL DEFAULT
	)
	LOGGING
	NOCOMPRESS
	NOCACHE
	NOPARALLEL
	NOROWDEPENDENCIES
	DISABLE ROW MOVEMENT;

COMMENT ON TABLE "ADDRESSBOOK" IS '주소록';

COMMENT ON COLUMN "ADDRESSBOOK"."ADDRBOOK_NO" IS '주소록번호';

COMMENT ON COLUMN "ADDRESSBOOK"."ADDRBOOK_NAME" IS '주소록이름';

COMMENT ON COLUMN "ADDRESSBOOK"."ADDRBOOK_COMNAME" IS '회사명';

COMMENT ON COLUMN "ADDRESSBOOK"."ADDRBOOK_TEL" IS '전화번호';

COMMENT ON COLUMN "ADDRESSBOOK"."ADDRBOOK_EMAIL" IS '이메일';

COMMENT ON COLUMN "ADDRESSBOOK"."MEM_NO" IS '사원번호';

CREATE UNIQUE INDEX "PK_ADDRESSBOOK"
	ON "ADDRESSBOOK" (
		"ADDRBOOK_NO" ASC
	)
	STORAGE (
		BUFFER_POOL DEFAULT
	)
	NOLOGGING
	NOCOMPRESS
	SORT
	NOPARALLEL;

ALTER TABLE "ADDRESSBOOK"
	ADD
		CONSTRAINT "PK_ADDRESSBOOK"
		PRIMARY KEY (
			"ADDRBOOK_NO"
		)
		NOT DEFERRABLE
		INITIALLY IMMEDIATE
		ENABLE
		VALIDATE;

/* 게시글목록 */
CREATE TABLE "BOARD" (
	"BOARD_NO" NUMBER NOT NULL, /* 게시글번호 */
	"MEM_NO" NUMBER, /* 사원번호 */
	"BDLIST_NO" NUMBER, /* 게시판번호 */
	"BOARD_TITLE" VARCHAR2(100) NOT NULL, /* 게시글제목 */
	"BOARD_CONTENT" VARCHAR2(3000), /* 게시들본문 */
	"BOARD_READCOUNT" NUMBER, /* 조회수 */
	"BOARD_REGDATE" DATE DEFAULT SYSDATE, /* 등록일 */
	"BOARD_CHANGEDATE" DATE, /* 수정일 */
	"BOARD_FILENAME" VARCHAR2(150), /* 업로드파일명 */
	"BOARD_FILESIZE" NUMBER, /* 파일사이즈 */
	"BOARD_ORIGINALFILENAME" VARCHAR2(150), /* 원본파일명 */
	"BOARD_DOWNCOUNT" NUMBER DEFAULT 0, /* 다운로드수 */
	"BOARD_DELFLAG" CHAR DEFAULT N, /* 삭제구분 */
	"BOARD_RECOMMEND" NUMBER DEFAULT 0 /* 추천수 */
)
	STORAGE (
		BUFFER_POOL DEFAULT
	)
	LOGGING
	NOCOMPRESS
	NOCACHE
	NOPARALLEL
	NOROWDEPENDENCIES
	DISABLE ROW MOVEMENT;

COMMENT ON TABLE "BOARD" IS '게시글목록';

COMMENT ON COLUMN "BOARD"."BOARD_NO" IS '게시글번호';

COMMENT ON COLUMN "BOARD"."MEM_NO" IS '사원번호';

COMMENT ON COLUMN "BOARD"."BDLIST_NO" IS '게시판번호';

COMMENT ON COLUMN "BOARD"."BOARD_TITLE" IS '게시글제목';

COMMENT ON COLUMN "BOARD"."BOARD_CONTENT" IS '게시들본문';

COMMENT ON COLUMN "BOARD"."BOARD_READCOUNT" IS '조회수';

COMMENT ON COLUMN "BOARD"."BOARD_REGDATE" IS '등록일';

COMMENT ON COLUMN "BOARD"."BOARD_CHANGEDATE" IS '수정일';

COMMENT ON COLUMN "BOARD"."BOARD_FILENAME" IS '업로드파일명';

COMMENT ON COLUMN "BOARD"."BOARD_FILESIZE" IS '파일사이즈';

COMMENT ON COLUMN "BOARD"."BOARD_ORIGINALFILENAME" IS '원본파일명';

COMMENT ON COLUMN "BOARD"."BOARD_DOWNCOUNT" IS '다운로드수';

COMMENT ON COLUMN "BOARD"."BOARD_DELFLAG" IS '삭제구분';

COMMENT ON COLUMN "BOARD"."BOARD_RECOMMEND" IS '추천수';

CREATE UNIQUE INDEX "PK_BOARD"
	ON "BOARD" (
		"BOARD_NO" ASC
	)
	STORAGE (
		BUFFER_POOL DEFAULT
	)
	NOLOGGING
	NOCOMPRESS
	SORT
	NOPARALLEL;

ALTER TABLE "BOARD"
	ADD
		CONSTRAINT "PK_BOARD"
		PRIMARY KEY (
			"BOARD_NO"
		)
		NOT DEFERRABLE
		INITIALLY IMMEDIATE
		ENABLE
		VALIDATE;

/* 게시판목록 */
CREATE TABLE "BOARDLIST" (
	"BDLIST_NO" NUMBER NOT NULL, /* 게시판번호 */
	"BDLIST_NAME" VARCHAR2(100), /* 게시판이름 */
	"BDLIST_RE" CHAR DEFAULT Y, /* 댓글허용 */
	"BDLIST_UP" CHAR DEFAULT Y, /* 업로드허용 */
	"BDLIST_RC" CHAR DEFAULT Y, /* 추천허용 */
	"RANKS_NO" NUMBER, /* 등급번호 */
	"BDLIST_REGDATE" DATE DEFAULT SYSDATE /* 등록일 */
)
	STORAGE (
		BUFFER_POOL DEFAULT
	)
	LOGGING
	NOCOMPRESS
	NOCACHE
	NOPARALLEL
	NOROWDEPENDENCIES
	DISABLE ROW MOVEMENT;

COMMENT ON TABLE "BOARDLIST" IS '게시판목록';

COMMENT ON COLUMN "BOARDLIST"."BDLIST_NO" IS '게시판번호';

COMMENT ON COLUMN "BOARDLIST"."BDLIST_NAME" IS '게시판이름';

COMMENT ON COLUMN "BOARDLIST"."BDLIST_RE" IS '댓글허용';

COMMENT ON COLUMN "BOARDLIST"."BDLIST_UP" IS '업로드허용';

COMMENT ON COLUMN "BOARDLIST"."BDLIST_RC" IS '추천허용';

COMMENT ON COLUMN "BOARDLIST"."RANKS_NO" IS '등급번호';

COMMENT ON COLUMN "BOARDLIST"."BDLIST_REGDATE" IS '등록일';

CREATE UNIQUE INDEX "PK_BOARDLIST"
	ON "BOARDLIST" (
		"BDLIST_NO" ASC
	)
	STORAGE (
		BUFFER_POOL DEFAULT
	)
	NOLOGGING
	NOCOMPRESS
	SORT
	NOPARALLEL;

ALTER TABLE "BOARDLIST"
	ADD
		CONSTRAINT "PK_BOARDLIST"
		PRIMARY KEY (
			"BDLIST_NO"
		)
		NOT DEFERRABLE
		INITIALLY IMMEDIATE
		ENABLE
		VALIDATE;

/* 댓글 */
CREATE TABLE "REPLY" (
	"REP_NO" NUMBER NOT NULL, /* 댓글번호 */
	"REP_CONTENT" VARCHAR2(500), /* 댓글본문 */
	"REP_REGDATE" DATE DEFAULT SYSDATE, /* 댓글등록일 */
	"REP_GROUP" NUMBER, /* 댓글그룹 */
	"REP_SORTNO" NUMBER, /* 댓글순서 */
	"REP_DEPTH" NUMBER, /* 댓글계층 */
	"REP_SECRET" CHAR DEFAULT N, /* 공개여부 */
	"MEM_NO" NUMBER, /* 사원번호 */
	"BOARD_NO" NUMBER /* 게시글번호 */
)
	STORAGE (
		BUFFER_POOL DEFAULT
	)
	LOGGING
	NOCOMPRESS
	NOCACHE
	NOPARALLEL
	NOROWDEPENDENCIES
	DISABLE ROW MOVEMENT;

COMMENT ON TABLE "REPLY" IS '댓글';

COMMENT ON COLUMN "REPLY"."REP_NO" IS '댓글번호';

COMMENT ON COLUMN "REPLY"."REP_CONTENT" IS '댓글본문';

COMMENT ON COLUMN "REPLY"."REP_REGDATE" IS '댓글등록일';

COMMENT ON COLUMN "REPLY"."REP_GROUP" IS '댓글그룹';

COMMENT ON COLUMN "REPLY"."REP_SORTNO" IS '댓글순서';

COMMENT ON COLUMN "REPLY"."REP_DEPTH" IS '댓글계층';

COMMENT ON COLUMN "REPLY"."REP_SECRET" IS '공개여부';

COMMENT ON COLUMN "REPLY"."MEM_NO" IS '사원번호';

COMMENT ON COLUMN "REPLY"."BOARD_NO" IS '게시글번호';

CREATE UNIQUE INDEX "PK_REPLY"
	ON "REPLY" (
		"REP_NO" ASC
	)
	STORAGE (
		BUFFER_POOL DEFAULT
	)
	NOLOGGING
	NOCOMPRESS
	SORT
	NOPARALLEL;

ALTER TABLE "REPLY"
	ADD
		CONSTRAINT "PK_REPLY"
		PRIMARY KEY (
			"REP_NO"
		)
		NOT DEFERRABLE
		INITIALLY IMMEDIATE
		ENABLE
		VALIDATE;

/* 결재라인 */
CREATE TABLE "CONFIRMLINE" (
	"LINE_NO" NUMBER NOT NULL, /* 라인번호 */
	"REG_NO" NUMBER, /* 등록번호 */
	"MEM_NO" NUMBER, /* 사원번호 */
	"LINE_ORDER" NUMBER /* 결제순서 */
)
	STORAGE (
		BUFFER_POOL DEFAULT
	)
	LOGGING
	NOCOMPRESS
	NOCACHE
	NOPARALLEL
	NOROWDEPENDENCIES
	DISABLE ROW MOVEMENT;

COMMENT ON TABLE "CONFIRMLINE" IS '결재라인';

COMMENT ON COLUMN "CONFIRMLINE"."LINE_NO" IS '라인번호';

COMMENT ON COLUMN "CONFIRMLINE"."REG_NO" IS '등록번호';

COMMENT ON COLUMN "CONFIRMLINE"."MEM_NO" IS '사원번호';

COMMENT ON COLUMN "CONFIRMLINE"."LINE_ORDER" IS '결제순서';

CREATE UNIQUE INDEX "PK_CONFIRMLINE"
	ON "CONFIRMLINE" (
		"LINE_NO" ASC
	)
	STORAGE (
		BUFFER_POOL DEFAULT
	)
	NOLOGGING
	NOCOMPRESS
	SORT
	NOPARALLEL;

ALTER TABLE "CONFIRMLINE"
	ADD
		CONSTRAINT "PK_CONFIRMLINE"
		PRIMARY KEY (
			"LINE_NO"
		)
		NOT DEFERRABLE
		INITIALLY IMMEDIATE
		ENABLE
		VALIDATE;

/* 자원 */
CREATE TABLE "REDOURCES" (
	"RES_NO" NUMBER NOT NULL, /* 자원번호 */
	"TYPE_NO" NUMBER, /* 종류번호 */
	"RES_NAME" VARCHAR2(100) NOT NULL, /* 자원명 */
	"RES_PRICE" NUMBER, /* 가격 */
	"RES_REGDATE" DATE DEFAULT SYSDATE, /* 등록일 */
	"RES_LOCATION" VARCHAR2(150), /* 자원위치 */
	"RES_FILENAME" VARCHAR2(150), /* 사진파일명 */
	"RES_ORIGINALFILENAME" VARCHAR2(150), /* 사진원본파일명 */
	"APPR_FLAG" CHAR DEFAULT A, /* 승인방식 */
	"RESERV_FLAG" CHAR DEFAULT N, /* 예약가능 */
	"RES_INFORMATION" VARCHAR2(150) /* 자원정보 */
)
	STORAGE (
		BUFFER_POOL DEFAULT
	)
	LOGGING
	NOCOMPRESS
	NOCACHE
	NOPARALLEL
	NOROWDEPENDENCIES
	DISABLE ROW MOVEMENT;

COMMENT ON TABLE "REDOURCES" IS '자원';

COMMENT ON COLUMN "REDOURCES"."RES_NO" IS '자원번호';

COMMENT ON COLUMN "REDOURCES"."TYPE_NO" IS '종류번호';

COMMENT ON COLUMN "REDOURCES"."RES_NAME" IS '자원명';

COMMENT ON COLUMN "REDOURCES"."RES_PRICE" IS '가격';

COMMENT ON COLUMN "REDOURCES"."RES_REGDATE" IS '등록일';

COMMENT ON COLUMN "REDOURCES"."RES_LOCATION" IS '자원위치';

COMMENT ON COLUMN "REDOURCES"."RES_FILENAME" IS '사진파일명';

COMMENT ON COLUMN "REDOURCES"."RES_ORIGINALFILENAME" IS '사진원본파일명';

COMMENT ON COLUMN "REDOURCES"."APPR_FLAG" IS '승인방식';

COMMENT ON COLUMN "REDOURCES"."RESERV_FLAG" IS '예약가능';

COMMENT ON COLUMN "REDOURCES"."RES_INFORMATION" IS '자원정보';

CREATE UNIQUE INDEX "PK_REDOURCES"
	ON "REDOURCES" (
		"RES_NO" ASC
	)
	STORAGE (
		BUFFER_POOL DEFAULT
	)
	NOLOGGING
	NOCOMPRESS
	SORT
	NOPARALLEL;

ALTER TABLE "REDOURCES"
	ADD
		CONSTRAINT "PK_REDOURCES"
		PRIMARY KEY (
			"RES_NO"
		)
		NOT DEFERRABLE
		INITIALLY IMMEDIATE
		ENABLE
		VALIDATE;

/* 자원스케줄 */
CREATE TABLE "RESSCHEDULE" (
	"RESERV_NO" NUMBER NOT NULL, /* 예약번호 */
	"MEM_NO" NUMBER, /* 사원번호 */
	"RES_NO" NUMBER, /* 자원번호 */
	"USE_REGDATE" DATE DEFAULT SYSDATE NOT NULL, /* 사용날짜 */
	"RETURN_REGDATE" DATE NOT NULL, /* 반납날짜 */
	"RESERV_CONTENT" VARCHAR2(300), /* 예약내용 */
	"APPR_FLAG" CHAR DEFAULT N /* 승인여부 */
)
	STORAGE (
		BUFFER_POOL DEFAULT
	)
	LOGGING
	NOCOMPRESS
	NOCACHE
	NOPARALLEL
	NOROWDEPENDENCIES
	DISABLE ROW MOVEMENT;

COMMENT ON TABLE "RESSCHEDULE" IS '자원스케줄';

COMMENT ON COLUMN "RESSCHEDULE"."RESERV_NO" IS '예약번호';

COMMENT ON COLUMN "RESSCHEDULE"."MEM_NO" IS '사원번호';

COMMENT ON COLUMN "RESSCHEDULE"."RES_NO" IS '자원번호';

COMMENT ON COLUMN "RESSCHEDULE"."USE_REGDATE" IS '사용날짜';

COMMENT ON COLUMN "RESSCHEDULE"."RETURN_REGDATE" IS '반납날짜';

COMMENT ON COLUMN "RESSCHEDULE"."RESERV_CONTENT" IS '예약내용';

COMMENT ON COLUMN "RESSCHEDULE"."APPR_FLAG" IS '승인여부';

CREATE UNIQUE INDEX "PK_RESSCHEDULE"
	ON "RESSCHEDULE" (
		"RESERV_NO" ASC
	)
	STORAGE (
		BUFFER_POOL DEFAULT
	)
	NOLOGGING
	NOCOMPRESS
	SORT
	NOPARALLEL;

ALTER TABLE "RESSCHEDULE"
	ADD
		CONSTRAINT "PK_RESSCHEDULE"
		PRIMARY KEY (
			"RESERV_NO"
		)
		NOT DEFERRABLE
		INITIALLY IMMEDIATE
		ENABLE
		VALIDATE;

/* 자원종류 */
CREATE TABLE "RESTYPE" (
	"TYPE_NO" NUMBER NOT NULL, /* 종류번호 */
	"TYPE_NAME" VARCHAR2(100) /* 종류이름 */
)
	STORAGE (
		BUFFER_POOL DEFAULT
	)
	LOGGING
	NOCOMPRESS
	NOCACHE
	NOPARALLEL
	NOROWDEPENDENCIES
	DISABLE ROW MOVEMENT;

COMMENT ON TABLE "RESTYPE" IS '자원종류';

COMMENT ON COLUMN "RESTYPE"."TYPE_NO" IS '종류번호';

COMMENT ON COLUMN "RESTYPE"."TYPE_NAME" IS '종류이름';

CREATE UNIQUE INDEX "PK_RESTYPE"
	ON "RESTYPE" (
		"TYPE_NO" ASC
	)
	STORAGE (
		BUFFER_POOL DEFAULT
	)
	NOLOGGING
	NOCOMPRESS
	SORT
	NOPARALLEL;

ALTER TABLE "RESTYPE"
	ADD
		CONSTRAINT "PK_RESTYPE"
		PRIMARY KEY (
			"TYPE_NO"
		)
		NOT DEFERRABLE
		INITIALLY IMMEDIATE
		ENABLE
		VALIDATE;

/* 근태관리 */
CREATE TABLE "COMMUTE" (
	"COM_NO" NUMBER NOT NULL, /* 근태관리번호 */
	"MEM_NO" NUMBER, /* 사원번호 */
	"COM_INDATE" DATE DEFAULT SYSDATE, /* 출근시간 */
	"COM_OUTDATE" DATE, /* 퇴근시간 */
	"COM_STATUS" CHAR /* 근무상태 */
)
	STORAGE (
		BUFFER_POOL DEFAULT
	)
	LOGGING
	NOCOMPRESS
	NOCACHE
	NOPARALLEL
	NOROWDEPENDENCIES
	DISABLE ROW MOVEMENT;

COMMENT ON TABLE "COMMUTE" IS '근태관리';

COMMENT ON COLUMN "COMMUTE"."COM_NO" IS '근태관리번호';

COMMENT ON COLUMN "COMMUTE"."MEM_NO" IS '사원번호';

COMMENT ON COLUMN "COMMUTE"."COM_INDATE" IS '출근시간';

COMMENT ON COLUMN "COMMUTE"."COM_OUTDATE" IS '퇴근시간';

COMMENT ON COLUMN "COMMUTE"."COM_STATUS" IS '근무상태';

CREATE UNIQUE INDEX "PK_COMMUTE"
	ON "COMMUTE" (
		"COM_NO" ASC
	)
	STORAGE (
		BUFFER_POOL DEFAULT
	)
	NOLOGGING
	NOCOMPRESS
	SORT
	NOPARALLEL;

ALTER TABLE "COMMUTE"
	ADD
		CONSTRAINT "PK_COMMUTE"
		PRIMARY KEY (
			"COM_NO"
		)
		NOT DEFERRABLE
		INITIALLY IMMEDIATE
		ENABLE
		VALIDATE;

/* 웹하드목록 */
CREATE TABLE "WEBHARD" (
	"WEB_NO" NUMBER NOT NULL, /* 웹하드번호 */
	"WEB_CATEGORY" VARCHAR2(50) /* 웹하드분류 */
)
	STORAGE (
		BUFFER_POOL DEFAULT
	)
	LOGGING
	NOCOMPRESS
	NOCACHE
	NOPARALLEL
	NOROWDEPENDENCIES
	DISABLE ROW MOVEMENT;

COMMENT ON TABLE "WEBHARD" IS '웹하드목록';

COMMENT ON COLUMN "WEBHARD"."WEB_NO" IS '웹하드번호';

COMMENT ON COLUMN "WEBHARD"."WEB_CATEGORY" IS '웹하드분류';

CREATE UNIQUE INDEX "PK_WEBHARD"
	ON "WEBHARD" (
		"WEB_NO" ASC
	)
	STORAGE (
		BUFFER_POOL DEFAULT
	)
	NOLOGGING
	NOCOMPRESS
	SORT
	NOPARALLEL;

ALTER TABLE "WEBHARD"
	ADD
		CONSTRAINT "PK_WEBHARD"
		PRIMARY KEY (
			"WEB_NO"
		)
		NOT DEFERRABLE
		INITIALLY IMMEDIATE
		ENABLE
		VALIDATE;

/* 결제파일 */
CREATE TABLE "CONFIRMFILE" (
	"FILE_NO" NUMBER NOT NULL, /* 파일번호 */
	"FILE_NAME" VARCHAR2(150), /* 파일명 */
	"FILE_ORIGINALNAME" VARCHAR2(150), /* 원본파일명 */
	"FILE_SIZE" NUMBER, /* 파일사이즈 */
	"CF_NO" NUMBER /* 문서번호 */
)
	STORAGE (
		BUFFER_POOL DEFAULT
	)
	LOGGING
	NOCOMPRESS
	NOCACHE
	NOPARALLEL
	NOROWDEPENDENCIES
	DISABLE ROW MOVEMENT;

COMMENT ON TABLE "CONFIRMFILE" IS '결제파일';

COMMENT ON COLUMN "CONFIRMFILE"."FILE_NO" IS '파일번호';

COMMENT ON COLUMN "CONFIRMFILE"."FILE_NAME" IS '파일명';

COMMENT ON COLUMN "CONFIRMFILE"."FILE_ORIGINALNAME" IS '원본파일명';

COMMENT ON COLUMN "CONFIRMFILE"."FILE_SIZE" IS '파일사이즈';

COMMENT ON COLUMN "CONFIRMFILE"."CF_NO" IS '문서번호';

CREATE UNIQUE INDEX "PK_CONFIRMFILE"
	ON "CONFIRMFILE" (
		"FILE_NO" ASC
	)
	STORAGE (
		BUFFER_POOL DEFAULT
	)
	NOLOGGING
	NOCOMPRESS
	SORT
	NOPARALLEL;

ALTER TABLE "CONFIRMFILE"
	ADD
		CONSTRAINT "PK_CONFIRMFILE"
		PRIMARY KEY (
			"FILE_NO"
		)
		NOT DEFERRABLE
		INITIALLY IMMEDIATE
		ENABLE
		VALIDATE;

/* 웹하드파일목록 */
CREATE TABLE "WEBHARDFILE" (
	"FILE_NO" NUMBER NOT NULL, /* 웹하드파일번호 */
	"WEB_NO" NUMBER, /* 웹하드번호 */
	"MEM_NO" NUMBER, /* 사원번호 */
	"FILE_NAME" VARCHAR2(150), /* 파일명 */
	"FILE_ORIGINALFILENAME" VARCHAR2(150), /* 원본파일명 */
	"FILE_FILESIZE" NUMBER, /* 파일사이즈 */
	"FILE_REGDATE" DATE DEFAULT SYSDATE, /* 등록일 */
	"FILE_DOWNCOUNT" NUMBER DEFAULT 0 /* 다운로드수 */
)
	STORAGE (
		BUFFER_POOL DEFAULT
	)
	LOGGING
	NOCOMPRESS
	NOCACHE
	NOPARALLEL
	NOROWDEPENDENCIES
	DISABLE ROW MOVEMENT;

COMMENT ON TABLE "WEBHARDFILE" IS '웹하드파일목록';

COMMENT ON COLUMN "WEBHARDFILE"."FILE_NO" IS '웹하드파일번호';

COMMENT ON COLUMN "WEBHARDFILE"."WEB_NO" IS '웹하드번호';

COMMENT ON COLUMN "WEBHARDFILE"."MEM_NO" IS '사원번호';

COMMENT ON COLUMN "WEBHARDFILE"."FILE_NAME" IS '파일명';

COMMENT ON COLUMN "WEBHARDFILE"."FILE_ORIGINALFILENAME" IS '원본파일명';

COMMENT ON COLUMN "WEBHARDFILE"."FILE_FILESIZE" IS '파일사이즈';

COMMENT ON COLUMN "WEBHARDFILE"."FILE_REGDATE" IS '등록일';

COMMENT ON COLUMN "WEBHARDFILE"."FILE_DOWNCOUNT" IS '다운로드수';

CREATE UNIQUE INDEX "PK_WEBHARDFILE"
	ON "WEBHARDFILE" (
		"FILE_NO" ASC
	)
	STORAGE (
		BUFFER_POOL DEFAULT
	)
	NOLOGGING
	NOCOMPRESS
	SORT
	NOPARALLEL;

ALTER TABLE "WEBHARDFILE"
	ADD
		CONSTRAINT "PK_WEBHARDFILE"
		PRIMARY KEY (
			"FILE_NO"
		)
		NOT DEFERRABLE
		INITIALLY IMMEDIATE
		ENABLE
		VALIDATE;

/* 결재라인등록 */
CREATE TABLE "LINEREG" (
	"REG_NO" NUMBER NOT NULL, /* 등록번호 */
	"REG_NAME" VARCHAR2(60), /* 등록이름 */
	"MEM_NO" NUMBER, /* 사원번호 */
	"LINE_DEL" CHAR /* 라인삭제여부 */
)
	STORAGE (
		BUFFER_POOL DEFAULT
	)
	LOGGING
	NOCOMPRESS
	NOCACHE
	NOPARALLEL
	NOROWDEPENDENCIES
	DISABLE ROW MOVEMENT;

COMMENT ON TABLE "LINEREG" IS '결재라인등록';

COMMENT ON COLUMN "LINEREG"."REG_NO" IS '등록번호';

COMMENT ON COLUMN "LINEREG"."REG_NAME" IS '등록이름';

COMMENT ON COLUMN "LINEREG"."MEM_NO" IS '사원번호';

COMMENT ON COLUMN "LINEREG"."LINE_DEL" IS '라인삭제여부';

CREATE UNIQUE INDEX "PK_LINEREG"
	ON "LINEREG" (
		"REG_NO" ASC
	)
	STORAGE (
		BUFFER_POOL DEFAULT
	)
	NOLOGGING
	NOCOMPRESS
	SORT
	NOPARALLEL;

ALTER TABLE "LINEREG"
	ADD
		CONSTRAINT "PK_LINEREG"
		PRIMARY KEY (
			"REG_NO"
		)
		NOT DEFERRABLE
		INITIALLY IMMEDIATE
		ENABLE
		VALIDATE;

/* 결제서명등록 */
CREATE TABLE "SIGNREG" (
	"MEM_NO" NUMBER NOT NULL, /* 사원번호 */
	"SIGN_FILENAME" VARCHAR2(150), /* 파일명 */
	"SIGN_FILESIZE" NUMBER, /* 파일사이즈 */
	"SIGN_ORIGINALFILENAME" VARCHAR2(150) /* 원본파일명 */
)
	STORAGE (
		BUFFER_POOL DEFAULT
	)
	LOGGING
	NOCOMPRESS
	NOCACHE
	NOPARALLEL
	NOROWDEPENDENCIES
	DISABLE ROW MOVEMENT;

COMMENT ON TABLE "SIGNREG" IS '결제서명등록';

COMMENT ON COLUMN "SIGNREG"."MEM_NO" IS '사원번호';

COMMENT ON COLUMN "SIGNREG"."SIGN_FILENAME" IS '파일명';

COMMENT ON COLUMN "SIGNREG"."SIGN_FILESIZE" IS '파일사이즈';

COMMENT ON COLUMN "SIGNREG"."SIGN_ORIGINALFILENAME" IS '원본파일명';

CREATE UNIQUE INDEX "PK_SIGNREG"
	ON "SIGNREG" (
		"MEM_NO" ASC
	)
	STORAGE (
		BUFFER_POOL DEFAULT
	)
	NOLOGGING
	NOCOMPRESS
	SORT
	NOPARALLEL;

ALTER TABLE "SIGNREG"
	ADD
		CONSTRAINT "PK_SIGNREG"
		PRIMARY KEY (
			"MEM_NO"
		)
		NOT DEFERRABLE
		INITIALLY IMMEDIATE
		ENABLE
		VALIDATE;

/* 전자결재 */
CREATE TABLE "CONFIRM" (
	"CF_NO" NUMBER NOT NULL, /* 문서번호 */
	"FORM_NO" NUMBER, /* 양식번호 */
	"MEM_NO" NUMBER, /* 사원번호 */
	"DEPT_NO" NUMBER, /* 부서번호 */
	"REG_NO" NUMBER, /* 등록번호 */
	"CF_TITLE" VARCHAR2(300) NOT NULL, /* 기안제목 */
	"CF_CONTENT" CLOB, /* 기안내용 */
	"CF_STATE" NUMBER, /* 기안상태 */
	"CF_FILE" CHAR DEFAULT N, /* 파일첨부여부 */
	"CF_TMPSTORAGE" CHAR DEFAULT N, /* 임시저장 */
	"CF_DEL" CHAR DEFAULT N, /* 문서삭제여부 */
	"CF_ORDER" NUMBER DEFAULT 1, /* 현재결재순서 */
	"CF_REGDATE" DATE DEFAULT SYSDATE, /* 기안일자 */
	"CF_OKDATE" DATE /* 승인일 */
)
	STORAGE (
		BUFFER_POOL DEFAULT
	)
	LOGGING
	NOCOMPRESS
	NOCACHE
	NOPARALLEL
	NOROWDEPENDENCIES
	DISABLE ROW MOVEMENT;

COMMENT ON TABLE "CONFIRM" IS '전자결재';

COMMENT ON COLUMN "CONFIRM"."CF_NO" IS '문서번호';

COMMENT ON COLUMN "CONFIRM"."FORM_NO" IS '양식번호';

COMMENT ON COLUMN "CONFIRM"."MEM_NO" IS '사원번호';

COMMENT ON COLUMN "CONFIRM"."DEPT_NO" IS '부서번호';

COMMENT ON COLUMN "CONFIRM"."REG_NO" IS '등록번호';

COMMENT ON COLUMN "CONFIRM"."CF_TITLE" IS '기안제목';

COMMENT ON COLUMN "CONFIRM"."CF_CONTENT" IS '기안내용';

COMMENT ON COLUMN "CONFIRM"."CF_STATE" IS '기안상태';

COMMENT ON COLUMN "CONFIRM"."CF_FILE" IS '파일첨부여부';

COMMENT ON COLUMN "CONFIRM"."CF_TMPSTORAGE" IS '임시저장';

COMMENT ON COLUMN "CONFIRM"."CF_DEL" IS '문서삭제여부';

COMMENT ON COLUMN "CONFIRM"."CF_ORDER" IS '현재결재순서';

COMMENT ON COLUMN "CONFIRM"."CF_REGDATE" IS '기안일자';

COMMENT ON COLUMN "CONFIRM"."CF_OKDATE" IS '승인일';

CREATE UNIQUE INDEX "PK_CONFIRM"
	ON "CONFIRM" (
		"CF_NO" ASC
	)
	STORAGE (
		BUFFER_POOL DEFAULT
	)
	NOLOGGING
	NOCOMPRESS
	SORT
	NOPARALLEL;

ALTER TABLE "CONFIRM"
	ADD
		CONSTRAINT "PK_CONFIRM"
		PRIMARY KEY (
			"CF_NO"
		)
		NOT DEFERRABLE
		INITIALLY IMMEDIATE
		ENABLE
		VALIDATE;

/* 문서양식 */
CREATE TABLE "DOCFORM" (
	"FORM_NO" NUMBER NOT NULL, /* 양식번호 */
	"FORM_NAME" VARCHAR2(60) NOT NULL, /* 양식이름 */
	"TYPE_NO" NUMBER, /* 양식분류번호 */
	"RANKS_NO" NUMBER, /* 양식등급번호 */
	"FORM_DEL" CHAR DEFAULT N /* 양식삭제여부 */
)
	STORAGE (
		BUFFER_POOL DEFAULT
	)
	LOGGING
	NOCOMPRESS
	NOCACHE
	NOPARALLEL
	NOROWDEPENDENCIES
	DISABLE ROW MOVEMENT;

COMMENT ON TABLE "DOCFORM" IS '문서양식';

COMMENT ON COLUMN "DOCFORM"."FORM_NO" IS '양식번호';

COMMENT ON COLUMN "DOCFORM"."FORM_NAME" IS '양식이름';

COMMENT ON COLUMN "DOCFORM"."TYPE_NO" IS '양식분류번호';

COMMENT ON COLUMN "DOCFORM"."RANKS_NO" IS '양식등급번호';

COMMENT ON COLUMN "DOCFORM"."FORM_DEL" IS '양식삭제여부';

CREATE UNIQUE INDEX "PK_DOCFORM"
	ON "DOCFORM" (
		"FORM_NO" ASC
	)
	STORAGE (
		BUFFER_POOL DEFAULT
	)
	NOLOGGING
	NOCOMPRESS
	SORT
	NOPARALLEL;

ALTER TABLE "DOCFORM"
	ADD
		CONSTRAINT "PK_DOCFORM"
		PRIMARY KEY (
			"FORM_NO"
		)
		NOT DEFERRABLE
		INITIALLY IMMEDIATE
		ENABLE
		VALIDATE;

/* 양식종류 */
CREATE TABLE "DOCTYPE" (
	"TYPE_NO" NUMBER NOT NULL, /* 양식분류번호 */
	"TYPE_NAME" VARCHAR2(60) NOT NULL, /* 양식분류이름 */
	"TYPE_DEL" CHAR DEFAULT N /* 양식분류삭제여부 */
)
	STORAGE (
		BUFFER_POOL DEFAULT
	)
	LOGGING
	NOCOMPRESS
	NOCACHE
	NOPARALLEL
	NOROWDEPENDENCIES
	DISABLE ROW MOVEMENT;

COMMENT ON TABLE "DOCTYPE" IS '양식종류';

COMMENT ON COLUMN "DOCTYPE"."TYPE_NO" IS '양식분류번호';

COMMENT ON COLUMN "DOCTYPE"."TYPE_NAME" IS '양식분류이름';

COMMENT ON COLUMN "DOCTYPE"."TYPE_DEL" IS '양식분류삭제여부';

CREATE UNIQUE INDEX "PK_DOCTYPE"
	ON "DOCTYPE" (
		"TYPE_NO" ASC
	)
	STORAGE (
		BUFFER_POOL DEFAULT
	)
	NOLOGGING
	NOCOMPRESS
	SORT
	NOPARALLEL;

ALTER TABLE "DOCTYPE"
	ADD
		CONSTRAINT "PK_DOCTYPE"
		PRIMARY KEY (
			"TYPE_NO"
		)
		NOT DEFERRABLE
		INITIALLY IMMEDIATE
		ENABLE
		VALIDATE;

/* 웹메일 */
CREATE TABLE "MAIL" (
	"MAIL_NO" NUMBER NOT NULL, /* 메일번호 */
	"MAIL_REV" NUMBER NOT NULL, /* 보낸사람 */
	"MAIL_REVADDR" VARCHAR2(90) NOT NULL, /* 보낸주소 */
	"MAIL_SENADDR" VARCHAR2(90) NOT NULL, /* 받는주소 */
	"MAIL_TITLE" VARCHAR2(150) NOT NULL, /* 메일제목 */
	"MAIL_CONTENT" CLOB, /* 메일내용 */
	"MAIL_FILENAME" VARCHAR2(150), /* 첨부파일명 */
	"MAIL_ORIGINALFILENAME" VARCHAR2(150), /* 원본첨부파일명 */
	"MAIL_FILESIZE" NUMBER, /* 첨부파일사이즈 */
	"MAIL_REGDATE" DATE DEFAULT SYSDATE /* 보낸날짜 */
)
	STORAGE (
		BUFFER_POOL DEFAULT
	)
	LOGGING
	NOCOMPRESS
	NOCACHE
	NOPARALLEL
	NOROWDEPENDENCIES
	DISABLE ROW MOVEMENT;

COMMENT ON TABLE "MAIL" IS '웹메일';

COMMENT ON COLUMN "MAIL"."MAIL_NO" IS '메일번호';

COMMENT ON COLUMN "MAIL"."MAIL_REV" IS '보낸사람';

COMMENT ON COLUMN "MAIL"."MAIL_REVADDR" IS '보낸주소';

COMMENT ON COLUMN "MAIL"."MAIL_SENADDR" IS '받는주소';

COMMENT ON COLUMN "MAIL"."MAIL_TITLE" IS '메일제목';

COMMENT ON COLUMN "MAIL"."MAIL_CONTENT" IS '메일내용';

COMMENT ON COLUMN "MAIL"."MAIL_FILENAME" IS '첨부파일명';

COMMENT ON COLUMN "MAIL"."MAIL_ORIGINALFILENAME" IS '원본첨부파일명';

COMMENT ON COLUMN "MAIL"."MAIL_FILESIZE" IS '첨부파일사이즈';

COMMENT ON COLUMN "MAIL"."MAIL_REGDATE" IS '보낸날짜';

CREATE UNIQUE INDEX "PK_MAIL"
	ON "MAIL" (
		"MAIL_NO" ASC
	)
	STORAGE (
		BUFFER_POOL DEFAULT
	)
	NOLOGGING
	NOCOMPRESS
	SORT
	NOPARALLEL;

ALTER TABLE "MAIL"
	ADD
		CONSTRAINT "PK_MAIL"
		PRIMARY KEY (
			"MAIL_NO"
		)
		NOT DEFERRABLE
		INITIALLY IMMEDIATE
		ENABLE
		VALIDATE;

/* 직급 */
CREATE TABLE "POSITION" (
	"POS_NO" NUMBER NOT NULL, /* 직급번호 */
	"POS_NAME" VARCHAR2(30) NOT NULL /* 직급명 */
)
	STORAGE (
		BUFFER_POOL DEFAULT
	)
	LOGGING
	NOCOMPRESS
	NOCACHE
	NOPARALLEL
	NOROWDEPENDENCIES
	DISABLE ROW MOVEMENT;

COMMENT ON TABLE "POSITION" IS '직급';

COMMENT ON COLUMN "POSITION"."POS_NO" IS '직급번호';

COMMENT ON COLUMN "POSITION"."POS_NAME" IS '직급명';

CREATE UNIQUE INDEX "PK_POSITION"
	ON "POSITION" (
		"POS_NO" ASC
	)
	STORAGE (
		BUFFER_POOL DEFAULT
	)
	NOLOGGING
	NOCOMPRESS
	SORT
	NOPARALLEL;

ALTER TABLE "POSITION"
	ADD
		CONSTRAINT "PK_POSITION"
		PRIMARY KEY (
			"POS_NO"
		)
		NOT DEFERRABLE
		INITIALLY IMMEDIATE
		ENABLE
		VALIDATE;

/* 팀내스케줄 */
CREATE TABLE "TABLE3" (
)
	STORAGE (
		BUFFER_POOL DEFAULT
	)
	LOGGING
	NOCOMPRESS
	NOCACHE
	NOPARALLEL
	NOROWDEPENDENCIES
	DISABLE ROW MOVEMENT;

COMMENT ON TABLE "TABLE3" IS '팀내스케줄';

/* 개인스케줄 */
CREATE TABLE "SCHEDULE" (
	"SCD_NO" NUMBER NOT NULL, /* 스케줄번호 */
	"MEM_NO" NUMBER, /* 사원번호 */
	"SCD_START" DATE NOT NULL, /* 시작날짜 */
	"SCD_END" DATE NOT NULL, /* 끝날짜 */
	"SCD_TITLE" VARCHAR2(60), /* 스케줄제목 */
	"SCD_CONTENT" VARCHAR2(300) /* 스케줄내용 */
)
	STORAGE (
		BUFFER_POOL DEFAULT
	)
	LOGGING
	NOCOMPRESS
	NOCACHE
	NOPARALLEL
	NOROWDEPENDENCIES
	DISABLE ROW MOVEMENT;

COMMENT ON TABLE "SCHEDULE" IS '개인스케줄';

COMMENT ON COLUMN "SCHEDULE"."SCD_NO" IS '스케줄번호';

COMMENT ON COLUMN "SCHEDULE"."MEM_NO" IS '사원번호';

COMMENT ON COLUMN "SCHEDULE"."SCD_START" IS '시작날짜';

COMMENT ON COLUMN "SCHEDULE"."SCD_END" IS '끝날짜';

COMMENT ON COLUMN "SCHEDULE"."SCD_TITLE" IS '스케줄제목';

COMMENT ON COLUMN "SCHEDULE"."SCD_CONTENT" IS '스케줄내용';

CREATE UNIQUE INDEX "PK_SCHEDULE"
	ON "SCHEDULE" (
		"SCD_NO" ASC
	)
	STORAGE (
		BUFFER_POOL DEFAULT
	)
	NOLOGGING
	NOCOMPRESS
	SORT
	NOPARALLEL;

ALTER TABLE "SCHEDULE"
	ADD
		CONSTRAINT "PK_SCHEDULE"
		PRIMARY KEY (
			"SCD_NO"
		)
		NOT DEFERRABLE
		INITIALLY IMMEDIATE
		ENABLE
		VALIDATE;

/* 팀스케줄 */
CREATE TABLE "TEAMSCHEDULE" (
	"TSCD_NO" NUMBER NOT NULL, /* 스케줄번호 */
	"MEM_NO" NUMBER, /* 사원번호 */
	"DEPT_NO" NUMBER, /* 부서번호 */
	"TSCD_START" DATE NOT NULL, /* 시작날짜 */
	"TSCD_END" DATE NOT NULL, /* 끝날짜 */
	"TSCD_TITLE" VARCHAR2(60), /* 스케줄제목 */
	"TSCD_CONTENT" VARCHAR2(300) /* 스케줄내용 */
)
	STORAGE (
		BUFFER_POOL DEFAULT
	)
	LOGGING
	NOCOMPRESS
	NOCACHE
	NOPARALLEL
	NOROWDEPENDENCIES
	DISABLE ROW MOVEMENT;

COMMENT ON TABLE "TEAMSCHEDULE" IS '팀스케줄';

COMMENT ON COLUMN "TEAMSCHEDULE"."TSCD_NO" IS '스케줄번호';

COMMENT ON COLUMN "TEAMSCHEDULE"."MEM_NO" IS '사원번호';

COMMENT ON COLUMN "TEAMSCHEDULE"."DEPT_NO" IS '부서번호';

COMMENT ON COLUMN "TEAMSCHEDULE"."TSCD_START" IS '시작날짜';

COMMENT ON COLUMN "TEAMSCHEDULE"."TSCD_END" IS '끝날짜';

COMMENT ON COLUMN "TEAMSCHEDULE"."TSCD_TITLE" IS '스케줄제목';

COMMENT ON COLUMN "TEAMSCHEDULE"."TSCD_CONTENT" IS '스케줄내용';

CREATE UNIQUE INDEX "PK_TEAMSCHEDULE"
	ON "TEAMSCHEDULE" (
		"TSCD_NO" ASC
	)
	STORAGE (
		BUFFER_POOL DEFAULT
	)
	NOLOGGING
	NOCOMPRESS
	SORT
	NOPARALLEL;

ALTER TABLE "TEAMSCHEDULE"
	ADD
		CONSTRAINT "PK_TEAMSCHEDULE"
		PRIMARY KEY (
			"TSCD_NO"
		)
		NOT DEFERRABLE
		INITIALLY IMMEDIATE
		ENABLE
		VALIDATE;

/* 쪽지수신 */
CREATE TABLE "MSGREV" (
	"MSGREV_NO" NUMBER NOT NULL, /* 수신번호 */
	"MEM_NO" NUMBER NOT NULL, /* 사원번호 */
	"MSG_NO" NUMBER NOT NULL, /* 쪽지번호 */
	"MSGREV_DEL" CHAR DEFAULT N, /* 삭제플레그 */
	"MSGREV_DATE" DATE /* 확인날짜 */
)
	STORAGE (
		BUFFER_POOL DEFAULT
	)
	LOGGING
	NOCOMPRESS
	NOCACHE
	NOPARALLEL
	NOROWDEPENDENCIES
	DISABLE ROW MOVEMENT;

COMMENT ON TABLE "MSGREV" IS '쪽지수신';

COMMENT ON COLUMN "MSGREV"."MSGREV_NO" IS '수신번호';

COMMENT ON COLUMN "MSGREV"."MEM_NO" IS '사원번호';

COMMENT ON COLUMN "MSGREV"."MSG_NO" IS '쪽지번호';

COMMENT ON COLUMN "MSGREV"."MSGREV_DEL" IS '삭제플레그';

COMMENT ON COLUMN "MSGREV"."MSGREV_DATE" IS '확인날짜';

CREATE UNIQUE INDEX "PK_MSGREV"
	ON "MSGREV" (
		"MSGREV_NO" ASC
	)
	STORAGE (
		BUFFER_POOL DEFAULT
	)
	NOLOGGING
	NOCOMPRESS
	SORT
	NOPARALLEL;

ALTER TABLE "MSGREV"
	ADD
		CONSTRAINT "PK_MSGREV"
		PRIMARY KEY (
			"MSGREV_NO"
		)
		NOT DEFERRABLE
		INITIALLY IMMEDIATE
		ENABLE
		VALIDATE;

/* 쪽지함 */
CREATE TABLE "MESSAGE" (
	"MSG_NO" NUMBER NOT NULL, /* 쪽지번호 */
	"MEM_NO" NUMBER, /* 보낸회원 */
	"MSG_TITLE" VARCHAR2(150) NOT NULL, /* 쪽지제목 */
	"MSG_CONTENT" VARCHAR2(3000), /* 쪽지내용 */
	"MSG_DEL" CHAR DEFAULT N, /* 삭제플레그 */
	"MSG_REGDATE" DATE DEFAULT SYSDATE /* 날짜 */
)
	STORAGE (
		BUFFER_POOL DEFAULT
	)
	LOGGING
	NOCOMPRESS
	NOCACHE
	NOPARALLEL
	NOROWDEPENDENCIES
	DISABLE ROW MOVEMENT;

COMMENT ON TABLE "MESSAGE" IS '쪽지함';

COMMENT ON COLUMN "MESSAGE"."MSG_NO" IS '쪽지번호';

COMMENT ON COLUMN "MESSAGE"."MEM_NO" IS '보낸회원';

COMMENT ON COLUMN "MESSAGE"."MSG_TITLE" IS '쪽지제목';

COMMENT ON COLUMN "MESSAGE"."MSG_CONTENT" IS '쪽지내용';

COMMENT ON COLUMN "MESSAGE"."MSG_DEL" IS '삭제플레그';

COMMENT ON COLUMN "MESSAGE"."MSG_REGDATE" IS '날짜';

CREATE UNIQUE INDEX "PK_MESSAGE"
	ON "MESSAGE" (
		"MSG_NO" ASC
	)
	STORAGE (
		BUFFER_POOL DEFAULT
	)
	NOLOGGING
	NOCOMPRESS
	SORT
	NOPARALLEL;

ALTER TABLE "MESSAGE"
	ADD
		CONSTRAINT "PK_MESSAGE"
		PRIMARY KEY (
			"MSG_NO"
		)
		NOT DEFERRABLE
		INITIALLY IMMEDIATE
		ENABLE
		VALIDATE;

ALTER TABLE "MEMBER"
	ADD
		CONSTRAINT "FK_RANKS_TO_MEMBER"
		FOREIGN KEY (
			"RANKS_NO"
		)
		REFERENCES "RANKS" (
			"RANKS_NO"
		)
		NOT DEFERRABLE
		INITIALLY IMMEDIATE
		ENABLE
		VALIDATE;

ALTER TABLE "MEMBER"
	ADD
		CONSTRAINT "FK_DEPARTMENT_TO_MEMBER"
		FOREIGN KEY (
			"DEPT_NO"
		)
		REFERENCES "DEPARTMENT" (
			"DEPT_NO"
		)
		NOT DEFERRABLE
		INITIALLY IMMEDIATE
		ENABLE
		VALIDATE;

ALTER TABLE "MEMBER"
	ADD
		CONSTRAINT "FK_POSITION_TO_MEMBER"
		FOREIGN KEY (
			"POS_NO"
		)
		REFERENCES "POSITION" (
			"POS_NO"
		)
		NOT DEFERRABLE
		INITIALLY IMMEDIATE
		ENABLE
		VALIDATE;

ALTER TABLE "ADDRESSBOOK"
	ADD
		CONSTRAINT "FK_MEMBER_TO_ADDRESSBOOK"
		FOREIGN KEY (
			"MEM_NO"
		)
		REFERENCES "MEMBER" (
			"MEM_NO"
		)
		NOT DEFERRABLE
		INITIALLY IMMEDIATE
		ENABLE
		VALIDATE;

ALTER TABLE "BOARD"
	ADD
		CONSTRAINT "FK_MEMBER_TO_BOARD"
		FOREIGN KEY (
			"MEM_NO"
		)
		REFERENCES "MEMBER" (
			"MEM_NO"
		)
		NOT DEFERRABLE
		INITIALLY IMMEDIATE
		ENABLE
		VALIDATE;

ALTER TABLE "BOARD"
	ADD
		CONSTRAINT "FK_BOARDLIST_TO_BOARD"
		FOREIGN KEY (
			"BDLIST_NO"
		)
		REFERENCES "BOARDLIST" (
			"BDLIST_NO"
		)
		NOT DEFERRABLE
		INITIALLY IMMEDIATE
		ENABLE
		VALIDATE;

ALTER TABLE "BOARDLIST"
	ADD
		CONSTRAINT "FK_RANKS_TO_BOARDLIST"
		FOREIGN KEY (
			"RANKS_NO"
		)
		REFERENCES "RANKS" (
			"RANKS_NO"
		)
		NOT DEFERRABLE
		INITIALLY IMMEDIATE
		ENABLE
		VALIDATE;

ALTER TABLE "REPLY"
	ADD
		CONSTRAINT "FK_MEMBER_TO_REPLY"
		FOREIGN KEY (
			"MEM_NO"
		)
		REFERENCES "MEMBER" (
			"MEM_NO"
		)
		NOT DEFERRABLE
		INITIALLY IMMEDIATE
		ENABLE
		VALIDATE;

ALTER TABLE "REPLY"
	ADD
		CONSTRAINT "FK_BOARD_TO_REPLY"
		FOREIGN KEY (
			"BOARD_NO"
		)
		REFERENCES "BOARD" (
			"BOARD_NO"
		)
		NOT DEFERRABLE
		INITIALLY IMMEDIATE
		ENABLE
		VALIDATE;

ALTER TABLE "CONFIRMLINE"
	ADD
		CONSTRAINT "FK_MEMBER_TO_CONFIRMLINE"
		FOREIGN KEY (
			"MEM_NO"
		)
		REFERENCES "MEMBER" (
			"MEM_NO"
		)
		NOT DEFERRABLE
		INITIALLY IMMEDIATE
		ENABLE
		VALIDATE;

ALTER TABLE "CONFIRMLINE"
	ADD
		CONSTRAINT "FK_LINEREG_TO_CONFIRMLINE"
		FOREIGN KEY (
			"REG_NO"
		)
		REFERENCES "LINEREG" (
			"REG_NO"
		)
		NOT DEFERRABLE
		INITIALLY IMMEDIATE
		ENABLE
		VALIDATE;

ALTER TABLE "REDOURCES"
	ADD
		CONSTRAINT "FK_RESTYPE_TO_REDOURCES"
		FOREIGN KEY (
			"TYPE_NO"
		)
		REFERENCES "RESTYPE" (
			"TYPE_NO"
		)
		NOT DEFERRABLE
		INITIALLY IMMEDIATE
		ENABLE
		VALIDATE;

ALTER TABLE "RESSCHEDULE"
	ADD
		CONSTRAINT "FK_MEMBER_TO_RESSCHEDULE"
		FOREIGN KEY (
			"MEM_NO"
		)
		REFERENCES "MEMBER" (
			"MEM_NO"
		)
		NOT DEFERRABLE
		INITIALLY IMMEDIATE
		ENABLE
		VALIDATE;

ALTER TABLE "RESSCHEDULE"
	ADD
		CONSTRAINT "FK_REDOURCES_TO_RESSCHEDULE"
		FOREIGN KEY (
			"RES_NO"
		)
		REFERENCES "REDOURCES" (
			"RES_NO"
		)
		NOT DEFERRABLE
		INITIALLY IMMEDIATE
		ENABLE
		VALIDATE;

ALTER TABLE "COMMUTE"
	ADD
		CONSTRAINT "FK_MEMBER_TO_COMMUTE"
		FOREIGN KEY (
			"MEM_NO"
		)
		REFERENCES "MEMBER" (
			"MEM_NO"
		)
		NOT DEFERRABLE
		INITIALLY IMMEDIATE
		ENABLE
		VALIDATE;

ALTER TABLE "CONFIRMFILE"
	ADD
		CONSTRAINT "FK_CONFIRM_TO_CONFIRMFILE"
		FOREIGN KEY (
			"CF_NO"
		)
		REFERENCES "CONFIRM" (
			"CF_NO"
		)
		NOT DEFERRABLE
		INITIALLY IMMEDIATE
		ENABLE
		VALIDATE;

ALTER TABLE "WEBHARDFILE"
	ADD
		CONSTRAINT "FK_WEBHARD_TO_WEBHARDFILE"
		FOREIGN KEY (
			"WEB_NO"
		)
		REFERENCES "WEBHARD" (
			"WEB_NO"
		)
		NOT DEFERRABLE
		INITIALLY IMMEDIATE
		ENABLE
		VALIDATE;

ALTER TABLE "WEBHARDFILE"
	ADD
		CONSTRAINT "FK_MEMBER_TO_WEBHARDFILE"
		FOREIGN KEY (
			"MEM_NO"
		)
		REFERENCES "MEMBER" (
			"MEM_NO"
		)
		NOT DEFERRABLE
		INITIALLY IMMEDIATE
		ENABLE
		VALIDATE;

ALTER TABLE "LINEREG"
	ADD
		CONSTRAINT "FK_MEMBER_TO_LINEREG"
		FOREIGN KEY (
			"MEM_NO"
		)
		REFERENCES "MEMBER" (
			"MEM_NO"
		)
		NOT DEFERRABLE
		INITIALLY IMMEDIATE
		ENABLE
		VALIDATE;

ALTER TABLE "SIGNREG"
	ADD
		CONSTRAINT "FK_MEMBER_TO_SIGNREG"
		FOREIGN KEY (
			"MEM_NO"
		)
		REFERENCES "MEMBER" (
			"MEM_NO"
		)
		NOT DEFERRABLE
		INITIALLY IMMEDIATE
		ENABLE
		VALIDATE;

ALTER TABLE "CONFIRM"
	ADD
		CONSTRAINT "FK_MEMBER_TO_CONFIRM"
		FOREIGN KEY (
			"MEM_NO"
		)
		REFERENCES "MEMBER" (
			"MEM_NO"
		)
		NOT DEFERRABLE
		INITIALLY IMMEDIATE
		ENABLE
		VALIDATE;

ALTER TABLE "CONFIRM"
	ADD
		CONSTRAINT "FK_DEPARTMENT_TO_CONFIRM"
		FOREIGN KEY (
			"DEPT_NO"
		)
		REFERENCES "DEPARTMENT" (
			"DEPT_NO"
		)
		NOT DEFERRABLE
		INITIALLY IMMEDIATE
		ENABLE
		VALIDATE;

ALTER TABLE "CONFIRM"
	ADD
		CONSTRAINT "FK_LINEREG_TO_CONFIRM"
		FOREIGN KEY (
			"REG_NO"
		)
		REFERENCES "LINEREG" (
			"REG_NO"
		)
		NOT DEFERRABLE
		INITIALLY IMMEDIATE
		ENABLE
		VALIDATE;

ALTER TABLE "CONFIRM"
	ADD
		CONSTRAINT "FK_DOCFORM_TO_CONFIRM"
		FOREIGN KEY (
			"FORM_NO"
		)
		REFERENCES "DOCFORM" (
			"FORM_NO"
		)
		NOT DEFERRABLE
		INITIALLY IMMEDIATE
		ENABLE
		VALIDATE;

ALTER TABLE "DOCFORM"
	ADD
		CONSTRAINT "FK_DOCTYPE_TO_DOCFORM"
		FOREIGN KEY (
			"TYPE_NO"
		)
		REFERENCES "DOCTYPE" (
			"TYPE_NO"
		)
		NOT DEFERRABLE
		INITIALLY IMMEDIATE
		ENABLE
		VALIDATE;

ALTER TABLE "DOCFORM"
	ADD
		CONSTRAINT "FK_RANKS_TO_DOCFORM"
		FOREIGN KEY (
			"RANKS_NO"
		)
		REFERENCES "RANKS" (
			"RANKS_NO"
		)
		NOT DEFERRABLE
		INITIALLY IMMEDIATE
		ENABLE
		VALIDATE;

ALTER TABLE "MAIL"
	ADD
		CONSTRAINT "FK_MEMBER_TO_MAIL"
		FOREIGN KEY (
			"MAIL_REV"
		)
		REFERENCES "MEMBER" (
			"MEM_NO"
		)
		NOT DEFERRABLE
		INITIALLY IMMEDIATE
		ENABLE
		VALIDATE;

ALTER TABLE "SCHEDULE"
	ADD
		CONSTRAINT "FK_MEMBER_TO_SCHEDULE"
		FOREIGN KEY (
			"MEM_NO"
		)
		REFERENCES "MEMBER" (
			"MEM_NO"
		)
		NOT DEFERRABLE
		INITIALLY IMMEDIATE
		ENABLE
		VALIDATE;

ALTER TABLE "TEAMSCHEDULE"
	ADD
		CONSTRAINT "FK_MEMBER_TO_TEAMSCHEDULE"
		FOREIGN KEY (
			"MEM_NO"
		)
		REFERENCES "MEMBER" (
			"MEM_NO"
		)
		NOT DEFERRABLE
		INITIALLY IMMEDIATE
		ENABLE
		VALIDATE;

ALTER TABLE "TEAMSCHEDULE"
	ADD
		CONSTRAINT "FK_DEPARTMENT_TO_TEAMSCHEDULE"
		FOREIGN KEY (
			"DEPT_NO"
		)
		REFERENCES "DEPARTMENT" (
			"DEPT_NO"
		)
		NOT DEFERRABLE
		INITIALLY IMMEDIATE
		ENABLE
		VALIDATE;

ALTER TABLE "MSGREV"
	ADD
		CONSTRAINT "FK_MESSAGE_TO_MSGREV"
		FOREIGN KEY (
			"MSG_NO"
		)
		REFERENCES "MESSAGE" (
			"MSG_NO"
		)
		NOT DEFERRABLE
		INITIALLY IMMEDIATE
		ENABLE
		VALIDATE;

ALTER TABLE "MSGREV"
	ADD
		CONSTRAINT "FK_MEMBER_TO_MSGREV"
		FOREIGN KEY (
			"MEM_NO"
		)
		REFERENCES "MEMBER" (
			"MEM_NO"
		)
		NOT DEFERRABLE
		INITIALLY IMMEDIATE
		ENABLE
		VALIDATE;

ALTER TABLE "MESSAGE"
	ADD
		CONSTRAINT "FK_MEMBER_TO_MESSAGE"
		FOREIGN KEY (
			"MEM_NO"
		)
		REFERENCES "MEMBER" (
			"MEM_NO"
		)
		NOT DEFERRABLE
		INITIALLY IMMEDIATE
		ENABLE
		VALIDATE;